services:
  server:
    image: hb.louislelievre.fr/domaj/domaj-server:latest
    container_name: domaj-server
    ports:
      - "${SERVER_PORT:-3000}:3000"
    volumes:
      - domaj-data:/data
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - domaj-server.env

  agent:
    image: hb.louislelievre.fr/domaj/domaj-agent:latest
    container_name: domaj-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    ports:
      - "${AGENT_PORT:-3001}:3001"
    env_file:
      - domaj-agent.env

volumes:
  domaj-data:
    driver: local
