services:
  httpd-7-behind:
    image: httpd:2.4.59
    container_name: httpd-7-behind
    restart: "no"

  httpd-5-behind:
    image: httpd:2.4.61
    container_name: httpd-5-behind
    restart: "no"

  httpd-4-behind:
    image: httpd:2.4.62
    container_name: httpd-4-behind
    restart: "no"
